# Generated by Django 4.2.14 on 2024-07-26 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generatedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('image_data', models.CharField(max_length=255)),
                ('insert_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
